name: Build

on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - run: where bash
        shell: bash
      - run: where pacman || echo Not found
        shell: bash
      - run: where mingw-get || echo Not found
        shell: bash
      - run: where gcc || echo Not found
        shell: bash
