name: Build

on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - run: where bash
        shell: bash
      - run: where mingw-get
        shell: bash
      - run: where gcc
        shell: bash
