name: Build

on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - run: where bash
        shell: bash
      - run: where pacman || echo Not found
        shell: bash
      - run: where mingw-get || echo Not found
        shell: bash
      - run: where gcc || echo Not found
        shell: bash
      - run: where make || echo Not found
        shell: bash
      - run: git log -- config/m-nt.h
      - run: |
         echo cp config/m-nt.h runtime/caml/m.h
         echo cp config/s-nt.h runtime/caml/s.h
         cp config/Makefile.mingw64 Makefile.config
        shell: bash
      - run: git submodule update --init
      - run: |
          make flexdll
          make world.opt
          make flexlink.opt
